# Numpy fundamentals

This notebook is intended to demonstrate some of the capabilities of Numpy arrays.

## Imports

In [1]:
import numpy as np

## Basic properties

In [2]:
# Create a new array with two dimensions: first dimension with length of 2 and second dimension with length of 3
nparray = np.array([[1., 0., 0.],[0., 1., 2.]])

In [3]:
# Show the number of dimensions (or ranks, as dimensions are known inside Numpy)
nparray.ndim

2

In [4]:
# Show the size of the array in each dimension
nparray.shape

(2, 3)

In [5]:
# The length of the shape is equal to the number of ranks, or dimensions
len(nparray.shape)

2

In [6]:
# The total number of elements in the array
nparray.size

6

In [7]:
# The product of the sizes of the ranks is equal to the total number of elements in the array
nparray.shape[0] * nparray.shape[1]

6

In [8]:
# The types of the elements in the array
nparray.dtype

dtype('float64')

In [9]:
# Size in bytes for each element in the array
nparray.itemsize

8

In [10]:
# Equivalent to the previous method of finding the size in bytes for each element in the array
nparray.dtype.itemsize

8

In [11]:
# Data buffer
nparray.data

## Data manipulation

In [12]:
# Create new array with evenly spaced elements using the arange method
nparray = np.arange(15)

In [13]:
# Reshape the array to have size 3 in the first dimension and size 5 in the second
nparray_reshaped = nparray.reshape(3, 5)

In [14]:
# Create array filled with zeros
np.zeros( (2, 3) )

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [15]:
# Create array filled with ones
np.ones( (2, 3) )

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [16]:
# Create array filled with random values, depending on the contents that are currently in the memory space being used
np.empty( (2, 3) )

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [17]:
# Create array with linspace. Preferable over arange to create floating point elements
np.linspace(0, 1, 10)

array([ 0.        ,  0.11111111,  0.22222222,  0.33333333,  0.44444444,
        0.55555556,  0.66666667,  0.77777778,  0.88888889,  1.        ])

In [18]:
# Print whole arrays
# np.set_printoptions(threshold='nan')

In [19]:
# Create two new arrays
a = np.arange(4)
b = np.array([4, 5, 6, 7])

In [20]:
# Sum element wise
a + b

array([ 4,  6,  8, 10])

In [21]:
# Subtract element wise
a - b

array([-4, -4, -4, -4])

In [22]:
# Multiply element wise
a * b

array([ 0,  5, 12, 21])

In [23]:
# Division element wise
a / b

array([ 0.        ,  0.2       ,  0.33333333,  0.42857143])

In [24]:
# Power element wise
a ** b

array([   0,    1,   64, 2187])

In [25]:
# Create two new multidimensional arrays
a = np.array([[0, 1], [2, 3]])
b = np.array([[1, 2], [3, 4]])

In [26]:
# Matrix multiplication
a.dot(b)

array([[ 3,  4],
       [11, 16]])

In [27]:
# Element wise multiplication
a * b

array([[ 0,  2],
       [ 6, 12]])

In [28]:
# Create new array by summing two arrays element wise
c = a + b

In [29]:
# Compute the sum of all values in all dimensions
c.sum()

16

In [30]:
# Compute the lowest value being stored in the array
c.min()

1

In [31]:
# Compute the largest value being stored in the array
c.max()

7

In [32]:
# Cumulative sum
c.cumsum()

array([ 1,  4,  9, 16])

In [33]:
# Sum of each column
c.sum(axis=0)

array([ 6, 10])

In [34]:
# Sum of each row
c.sum(axis=1)

array([ 4, 12])

In [35]:
# Slicing a multidimensional array
c[:1,:]

array([[1, 3]])

In [36]:
# Get all elements within a dimension
c[:, ...]

array([[1, 3],
       [5, 7]])

In [37]:
# Iterator to run on all elements within a multidimensional array
c.flat

In [38]:
# Flat array
c.ravel()

array([1, 3, 5, 7])

In [39]:
# Copy an array
d = c.copy()

In [40]:
# Change the length of dimensions
d.resize( (3, 3) )

In [41]:
d

array([[1, 3, 5],
       [7, 0, 0],
       [0, 0, 0]])

In [42]:
# Create new array with 3 dimensions
a = np.arange(9).reshape(3, 3)

In [43]:
# Create new array with 3 dimensions
b = np.arange(9).reshape(3, 3)

In [44]:
# Stack both arrays horizontally
np.hstack( (a, b) )

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [45]:
# Stack both arrays vertically
np.vstack( (a, b) )

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [46]:
# Highest index in array
a.argmax()

8

In [47]:
# Create array with random elements
np.random.random(10)

array([ 0.99718832,  0.95701139,  0.08206546,  0.93099082,  0.38238192,
        0.75971826,  0.78885163,  0.89440313,  0.14332563,  0.84355728])